# .github/workflows/full_data_refresh.yml

name: Refresh Completo Dati Storici (Annuale/Manuale)

on:
  # Questo workflow si avvia SOLO manualmente.
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # Aumentiamo il timeout a 3 ore, perché questo job è lungo
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Installazione dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esecuzione script di refresh completo
        env:
          # Passiamo l'intero JSON come una singola variabile d'ambiente
          GDRIVE_SA_KEY: ${{ secrets.GDRIVE_SA_KEY }}
          EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
        run: python run_full_refresh.py

